name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  run:
    name: build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - macos-13
        setup-version:
          - v2
          - v3
        ocaml-compiler:
          - 4.06.x
          - 4.14.x
          - 5.1.x
        exclude:
          - os: ubuntu-latest
            setup-version: v2
          - os: macos-13
            setup-version: v3
          - os: macos-latest
            setup-version: v2
          - os: macos-latest
            ocaml-compiler: 4.06.x
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ocaml/setup-ocaml@v2
      if: matrix.setup-version == 'v2'
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
        allow-prerelease-opam: true
    - uses: ocaml/setup-ocaml@v3
      if: matrix.setup-version == 'v3'
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
        allow-prerelease-opam: true
    - run: opam pin -n .
    - run: opam install -t . --deps-only
    - run: opam exec -- dune build --ignore-promoted-rules
    - run: opam exec -- dune runtest --ignore-promoted-rules
